### ISSUE TITLE
Test repo documentation

### ISSUE THREAD

**Issue by FabioBergonti** [ami-iit/paper_bergonti_2022_tro_kinematics-control-morphingcovers#8]
In this issue, the documentation and code of this repo are going to be tested.

**Comment by claudia-lat** [comment]
I've tested the repo.  Few comments below:

### Installation
 I’ve ran the `install()` function without  `'env_name', 'imorph'` inputs (this took time), since as soon as I read the line at point 2 I’ve launched the command.  Maybe you can find a way to avoid this user's mistake.

### Usage
I’ve launched all of the 4 simulations.  Some of them were very fast (e.g., `sim1`), others very very long (e.g., `sim3`).  To let the user know about this you could:
- Add a printed message in the command windows about the status of the simulation/visualization.  For example in `sim3`, it took a while before showing something in the command window. And I thought nothing was happening.
- Add somewhere in the README (e.g., columns in the table of sims?) the estimated time, both for simulation and visualization.

**Comment by FabioBergonti** [comment]
Thanks @claudia-lat!
I opened two PRs, #7 and #8, that should address your comments

> I’ve ran the `install()` function without `'env_name', 'imorph'` inputs (this took time), since as soon as I read the line at point 2 I’ve launched the command. Maybe you can find a way to avoid this user's mistake.

The option `'env_name', 'imorph'` defines the name of the mamba environment. However, if you don't declare it, the default name is selected. To simplify the procedure I decided to remove `'env_name', 'imorph'` and to use the default name (`mystica`).

Fixed in #9 

> Add a printed message in the command windows about the status of the simulation/visualization. For example in sim3, it took a while before showing something in the command window. And I thought nothing was happening.

Fixed in #7 

> Add somewhere in the README (e.g., columns in the table of sims?) the estimated time, both for simulation and visualization.

Good idea. Added in the columns in the table of sims in #9

**Comment by FabioBergonti** [comment]
Thanks again @claudia-lat!
